### ISSUE TITLE
Unsetted env_var PATH crash

### ISSUE THREAD

**Issue by sansho88** [sansho88/Minishell#47]
When PATH is unset, and a not built-ins command is launched, Conchito exits itself

<img width="235" alt="image" src="https://user-images.githubusercontent.com/1939201/193620508-a3d103f0-73f6-40e5-94b4-6554a4c52c75.png">

**Comment by sansho88** [comment]
```BASH
env -i ./minishell
```
Cause: env is NULL.

J'ai fait plusieurs tests niveau parsing, en passant dans chacune de mes fonctions, et ça crash après être entré dans exec_home().
Le code-retour de Conchito post-crash est: 1.

**Comment by Chicanoss** [comment]
Solved.
