### ISSUE TITLE
"bad outfile heyo: Resource temporarily unavailable"

### ISSUE THREAD

**Issue by sansho88** [sansho88/Minishell#49]
```BASH
echo a > out | cat << EOF >> out | ls >> out
```
<img width="476" alt="image" src="https://user-images.githubusercontent.com/1939201/193855852-98f0e2df-b380-4a64-a93e-73cf5b26f453.png">

(je m'occupe du EOFFFFF qui va trop loin)

**Comment by Chicanoss** [comment]
Fixed
