### ISSUE TITLE
cat > a then CTRL+C

### ISSUE THREAD

**Issue by Chicanoss** [sansho88/Minishell#53]
<img width="341" alt="Capture d’écran 2022-10-09 à 17 12 47" src="https://user-images.githubusercontent.com/16854227/194764612-4ce14d70-5b86-4ddf-899c-b34b7ba77287.png">

**Comment by sansho88** [comment]
Fixed since [Double Conchito when SIG_INT in canonical-mode fixed](https://github.com/sansho88/Minishell/commit/fac3356457456fdd9d2f9f3189901eb34e26ec2b)
