### ISSUE TITLE
/////// should return a parsing error

### ISSUE THREAD

**Issue by Chicanoss** [sansho88/Minishell#87]

**Comment by sansho88** [comment]
See [ae30bdb](https://github.com/sansho88/Minishell/commit/ae30bdbf3af60d70d003cd2b6e700dea888a0c87) for some inspiration (is_chars_orgy(char *cmdline))

**Comment by sansho88** [comment]
Fixed since [edcb34217b49b65f1932d7e9734c26009f86c579](https://github.com/sansho88/Minishell/commit/edcb34217b49b65f1932d7e9734c26009f86c579)
